name: siperan-app

services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    ports:
      - "3007:3007"
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"

      # HTTP router only
      - traefik.http.routers.web-http.rule=Host(`1petapasar.manajemenprodukbaru-pg.com`)
      - traefik.http.routers.web-http.entrypoints=http
      - traefik.http.routers.web-http.tls=false

      # Service
      - traefik.http.services.web.loadbalancer.server.port=3007
    networks:
      - coolify
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASS:-password}@${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-siperan_db}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - NODE_ENV=production
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: siperan-app-postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-siperan_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-password}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - siperan_app_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  coolify:
    external: true

volumes:
  siperan_app_postgres_data:
